### ISSUE TITLE
FRONTEND : short tutorial of how to use our page

### ISSUE THREAD

**Issue by tomekl007** [tomekl007/initlearn#4]

**Comment by tomekl007** [comment]
https://upload.wikimedia.org/wikibooks/uk/8/85/Scala_logo.png

**Comment by tomekl007** [comment]
https://upload.wikimedia.org/wikipedia/en/8/88/Java_logo.png

**Comment by czosnek7** [comment]
1. skills
2. teachers
3. calendar
4. schedule
5. screenhero

Why learning in pair ?

**Comment by tomekl007** [comment]
https://www.youtube.com/watch?v=-zuyVK43LlM

**Comment by tomekl007** [comment]
https://www.youtube.com/watch?v=-zuyVK43LlM
