### ISSUE TITLE
FRONTEND : About us page with crawable description of what we do

### ISSUE THREAD

**Issue by tomekl007** [tomekl007/initlearn#81]
Obviously, if you want your page to have a chance of ranking in the search results for "dog," it's wise to make sure the word "dog" is part of the crawlable content of your document

**Comment by tomekl007** [comment]
subtask of https://github.com/tomekl007/initlearn/issues/8

**Comment by tomekl007** [comment]
Our site is an individual code school. You could find a teacher that will conduct individual programming lesson with you. Would you want to learn coding using pair programming technics and especially designed tools for that purpose, join us and we will help you with gathering staggering coding skills.

**Comment by tomekl007** [comment]
@czosnek7 place it on landing page

**Comment by czosnek7** [comment]
https://www.codeschool.com/
https://www.upwork.com/

**Comment by tomekl007** [comment]
![how_code_works](https://cloud.githubusercontent.com/assets/2332235/13900032/d50c07d6-edfc-11e5-8672-1b737b5ba457.jpg)

**Comment by tomekl007** [comment]
https://www.dropbox.com/sh/167e5r3xhy1fv3g/AAANsVspoFrjnfJ9uFIW8h75a?dl=0

**Comment by tomekl007** [comment]
1.find teacher by skill that you want to learn  - searchbar.png
2.schedule appoitment  - schedule.png
3.learn programming in pair programming fashion by cooperating with teacher - Online_learning_pp.png

**Comment by tomekl007** [comment]
1.Search for technology
You want to learn javaScript ? Type in a search bar and find a teacher

2.Find a teacher
From our teachers find one that has best rating! He will teach you a particular skill

3.Choose time
Go to teacher schedule, and find time that suits you best. Make a reservation to have scheduled appointment with your teacher

4.See all of your appointments 
You can easily manage your appointments with our teachers. Everything in one place !

5.Learn programming in pair programming fashion
Together with your teacher using best tools for online learning achieve next milestones on your programming path

**Comment by tomekl007** [comment]
Why learn with initLearn?
At initLearn our teachers are learning programming in pair programming fashion.
When you make an appointment for one hour, teacher will devote whole hour only for you.
Lesson will be conducted one on one, with focus on cooperation between you and your teacher.
You will be writing real computer programs from first hour and you will see effects of your work instantly.
